apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-bzvq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-vgwi-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-bzvq@sha256:400c0ac63f0ed0b303098da6eb50c56ee2f3814b4daa84257f1a3b120c397398
        name: my-python
        resources: {}
status: {}
